- name: Prequisites
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Get list of directories to create
      set_fact:
        directories: "{{dirs_to_create | from_json}}"
    - name: Create directories
      file:
        # accepted input for containers: volumes with format path:mountpoint
        # in which case, only the first element has to be created
        path: item.split(':')[0]
        state: directory
        recurse: yes
        mode: 0777
      loop: "{{ directories }}"
