- name: "CreaRunningting script"
  hosts: all
  strategy: linear
  tasks:
    - name: Download webdrops data
      shell: /tmp/lexis_exec_script.sh
      environment: "{{ TOSCA_ENV_VARS_INPUT }}"
      register: execRes
    - debug: var=execRes.stdout_lines
    - name: Set STDOUT and STDERR (operation outputs)
      set_fact:
        STDOUT: "{{ execRes.stdout }}"
        STDERR: "{{ execRes.stderr }}"
