- name: Install dependencies
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: RedHat -  install git
      dnf:
        name:
          - git
        state: present
      when: ansible_os_family == 'RedHat'
    - name: Debian - install git
      apt:
        name:
          - git
        state: present
        update_cache: yes
      register: apt_res
      retries: 3
      until: apt_res is success
      when: ansible_os_family == 'Debian'
